version: '3.8'

services:
  db:
    image: postgres:15
    container_name: listings_db
    environment:
      - POSTGRES_DB=listings_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

#  listings-app:
#   image: listings-app
#   build:
#       context: .
#       dockerfile: Dockerfile
#   depends_on:
#     - db
#   ports:
#     - "8081:8081"
#   environment:
#     SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/listings_db
#     SPRING_DATASOURCE_USERNAME: postgres
#     SPRING_DATASOURCE_PASSWORD: postgres

volumes:
  dbdata:
